name: Windows RDP via Tailscale

on:
  workflow_dispatch:

jobs:
  windows-rdp:
    runs-on: windows-latest
    timeout-minutes: 120  # maks 2 jam supaya kamu sempat konek

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download Tailscale
      run: |
        Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-ipn-setup.exe" -OutFile "tailscale-installer.exe"
        Start-Process -FilePath .\tailscale-installer.exe -ArgumentList "/quiet" -Wait

    - name: Start Tailscaled service
      run: |
        Start-Service Tailscale
        Start-Service TailscaleService
        Start-Sleep -Seconds 5
        tailscale status || echo "Service started"

    - name: Authenticate Tailscale
      env:
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      run: |
        tailscale up --authkey "$env:TAILSCALE_AUTHKEY" --hostname "win-runner-${env:GITHUB_RUN_ID}" --accept-dns=false --accept-routes=true
        tailscale ip -4

    - name: Enable RDP and firewall rules
      run: |
        # Pastikan RDP aktif
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Get-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Show connection info
      run: |
        Write-Host "=================================="
        Write-Host "Tailscale IP (gunakan di RDP):"
        tailscale ip -4
        Write-Host "=================================="
        Write-Host "Username default RDP: runneradmin"
        Write-Host "Password: lihat langkah berikut"
        Write-Host "=================================="

    - name: Show RDP password
      run: |
        $pass = (Get-ChildItem Env: | Where-Object {$_.Name -eq "RDPPASSWORD"}).Value
        if (-not $pass) {
          $pass = [guid]::NewGuid().ToString().Substring(0,8)
          Write-Host "Generated password: $pass"
        } else {
          Write-Host "Password from env: $pass"
        }

    - name: Keep session alive
      run: |
        Write-Host "RDP aktif. Gunakan Tailscale IP di atas + user runneradmin"
        Write-Host "Job akan sleep selama 90 menit..."
        Start-Sleep -Seconds 5400
