name: Windows RDP with Tailscale

on:
  workflow_dispatch:  # Jalanin manual dari GitHub UI

jobs:
  setup-rdp:
    runs-on: windows-latest
    timeout-minutes: 360  # 6 jam, sesuaikan

    steps:
      - name: Install and Connect Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENTID }}
          oauth-secret: ${{ secrets.TAILSCALE_SECRET }}
          tags: tag:actions  # Tag buat ACL di Tailscale

      - name: Enable RDP
        run: |
          # Enable RDP connections
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          # Enable firewall rules for RDP
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          # Require user authentication for security
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          # Set password for default admin user (runneradmin)
          $password = ConvertTo-SecureString -AsPlainText "${{ secrets.USER_PASSWORD }}" -Force
          Set-LocalUser -Name "Administrator" -Password $password  # Ganti ke "runneradmin" kalo user lain

      - name: Get Tailscale IP and Hang
        run: |
          # Print Tailscale IP buat RDP (catat ini!)
          tailscale ip -4
          # Hang around biar runner tetep hidup (ganti durasi kalo perlu)
          Start-Sleep -Seconds 21600  # 6 jam
